### ISSUE TITLE
GitHub Pages 等にアプリをデプロイするといいかも

### ISSUE THREAD

**Issue by kamataryo** [YUUKIToriyama/imageCompare#3]
アプリのファイル一式を GitHub Pages などのホスティングサービス上で公開するといいかもです。
[GitHub Actions](https://github.com/features/actions) を使うと、`master` ブランチにコードをプッシュ -> React アプリをビルド -> GitHub Pages として公開 というワークフローを自動化することができます。

[peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) のようなアクションを使うと便利です。

**Comment by YuukiToriyama** [comment]
@kamataryo ありがとうございます。
GithubActionsを使うのは初めてですこし戸惑ったのですが、教えていただいたpeaceiris/actions-gh-pagesを使ったら簡単に設定できました。
自動的にビルドしてGithubPagesに公開してくれるのはとても便利ですね。

[https://yuukitoriyama.github.io/imageCompare/build/](https://yuukitoriyama.github.io/imageCompare/build/)

**Comment by kamataryo** [comment]
ビルドとデプロイ以外にも、通知したり、なんでもできるので、おもしろい使い方見つけたら教えてください！
